#!/usr/bin/env sh
# ==============================================================================
# Xergon Network Installer
# One-liner: curl -sSL https://degens.world/xergon | sh
#
# Supports: install, update, uninstall
# Dependencies: curl, tar, sh (standard Unix)
# ==============================================================================

set -e

# ── Constants ──────────────────────────────────────────────────────────────────

XERGON_VERSION="${XERGON_VERSION:-latest}"
XERGON_REPO="n1ur0/Xergon-Network"
XERGON_BASE_URL="https://github.com/${XERGON_REPO}/releases"
BINARY_NAME="xergon-agent"

# Directory structure
XERGON_HOME="${HOME}/.xergon"
XERGON_BIN="${XERGON_HOME}/bin"
XERGON_DATA="${XERGON_HOME}/data"

# ── Color Support ──────────────────────────────────────────────────────────────

# Auto-detect terminal color support
if [ -t 1 ]; then
    SUPPORTS_COLOR=1
else
    SUPPORTS_COLOR=0
fi

# Define colors (only output ANSI when terminal supports it)
if [ "$SUPPORTS_COLOR" -eq 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    BLUE='\033[0;34m'
    MAGENTA='\033[0;35m'
    CYAN='\033[0;36m'
    BOLD='\033[1m'
    DIM='\033[2m'
    RESET='\033[0m'
else
    RED=''
    GREEN=''
    YELLOW=''
    BLUE=''
    MAGENTA=''
    CYAN=''
    BOLD=''
    DIM=''
    RESET=''
fi

# ── Logging Helpers ────────────────────────────────────────────────────────────

info()  { printf "${GREEN}${BOLD}[INFO]${RESET}  %s\n" "$*"; }
warn()  { printf "${YELLOW}${BOLD}[WARN]${RESET}  %s\n" "$*"; }
error() { printf "${RED}${BOLD}[ERROR]${RESET} %s\n" "$*" >&2; }
step()  { printf "${CYAN}${BOLD}  →${RESET} %s\n" "$*"; }
success() { printf "${GREEN}${BOLD}  ✓${RESET} %s\n" "$*"; }
banner() {
    printf "\n"
    printf "${BOLD}${MAGENTA}  ╔══════════════════════════════════════╗${RESET}\n"
    printf "${BOLD}${MAGENTA}  ║${RESET}${BOLD}       XERGON NETWORK INSTALLER      ${RESET}${BOLD}${MAGENTA}║${RESET}\n"
    printf "${BOLD}${MAGENTA}  ║${RESET}${DIM}  Decentralized AI on Ergo Blockchain ${RESET}${BOLD}${MAGENTA}║${RESET}\n"
    printf "${BOLD}${MAGENTA}  ╚══════════════════════════════════════╝${RESET}\n"
    printf "\n"
}

# ── OS / Arch Detection ────────────────────────────────────────────────────────

detect_os() {
    OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
    case "$OS" in
        linux)  OS="linux" ;;
        darwin) OS="darwin" ;;
        *)
            error "Unsupported operating system: ${OS}"
            error "Xergon supports Linux and macOS."
            exit 1
            ;;
    esac
}

detect_arch() {
    ARCH="$(uname -m)"
    case "$ARCH" in
        x86_64|amd64) ARCH="amd64" ;;
        aarch64|arm64) ARCH="arm64" ;;
        *)
            error "Unsupported architecture: ${ARCH}"
            error "Xergon supports amd64 and arm64."
            exit 1
            ;;
    esac
}

# ── Prerequisite Checks ────────────────────────────────────────────────────────

check_prereqs() {
    step "Checking prerequisites..."

    for cmd in curl tar sh; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            error "Required command not found: ${cmd}"
            error "Please install ${cmd} and try again."
            exit 1
        fi
    done

    success "All prerequisites met"
}

# ── Directory Structure ────────────────────────────────────────────────────────

create_dirs() {
    step "Creating directory structure..."

    mkdir -p "${XERGON_BIN}"
    mkdir -p "${XERGON_DATA}"

    success "~/.xergon/bin/  (binaries)"
    success "~/.xergon/data/ (ledger, peers)"
}

# ── Config File ────────────────────────────────────────────────────────────────

generate_default_config() {
    local config_path="${XERGON_HOME}/config.toml"

    if [ -f "${config_path}" ]; then
        step "Existing config found, preserving: ${config_path}"
        return 0
    fi

    step "Generating default config..."
    cat > "${config_path}" << 'EOF'
# Xergon Agent Configuration
# Generated by installer -- edit freely or run: xergon-agent setup

[agent]
# Your chosen provider name (shown on leaderboard)
name = "anonymous"

# Region code for routing (us-east, eu-west, ap-east, etc.)
region = "us-east"

# GPU mode: "mine-serve" or "serve-only"
gpu_mode = "mine-serve"

[ergo]
# Ergo node URL (local node default)
node_url = "http://127.0.0.1:9053"

# Relay URL
relay_url = "https://relay.xergon.gg"

[ai]
# AI backend: "ollama", "llama.cpp", "tinygrad", "custom"
backend = "ollama"

# Backend URL (auto-detected during setup)
backend_url = "http://127.0.0.1:11434"

# Models to serve (comma-separated or leave empty for all)
models = []

[settlement]
# Settlement interval in seconds
interval_seconds = 3600

# Minimum ERG balance before auto-settlement
min_balance_nanoerg = 1000000000

[logging]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"
EOF

    success "Default config written: ${config_path}"
}

# ── Wallet Placeholder ─────────────────────────────────────────────────────────

create_wallet_placeholder() {
    local wallet_path="${XERGON_HOME}/wallet.json"

    if [ -f "${wallet_path}" ]; then
        step "Existing wallet found, preserving: ${wallet_path}"
        return 0
    fi

    step "Creating wallet placeholder..."
    cat > "${wallet_path}" << 'EOF'
{
  "encrypted_keypair": null,
  "public_address": null,
  "created_at": null,
  "note": "Run 'xergon-agent setup' to generate your wallet"
}
EOF

    success "Wallet placeholder written: ${wallet_path}"
}

# ── PATH Setup ─────────────────────────────────────────────────────────────────

path_entry='export PATH="$HOME/.xergon/bin:$PATH"'
path_marker='# XERGON-NETWORK-PATH'

add_to_path() {
    local added=0

    # Helper: add PATH entry to a file if not already present
    _add_to_file() {
        local target_file="$1"
        if [ -f "$target_file" ]; then
            if grep -qF "${path_marker}" "$target_file" 2>/dev/null; then
                step "PATH already in ${target_file}, skipping"
            else
                printf '\n%s\n%s\n' "${path_marker}" "${path_entry}" >> "$target_file"
                success "Added PATH to ${target_file}"
                added=1
            fi
        fi
    }

    step "Configuring PATH in shell profile..."

    # Prefer the shell we're actually running in, but check others too
    _add_to_file "${HOME}/.zshrc"
    _add_to_file "${HOME}/.bashrc"
    _add_to_file "${HOME}/.bash_profile"
    _add_to_file "${HOME}/.profile"

    if [ "$added" -eq 0 ]; then
        # If none of the files exist, create .profile
        if [ ! -f "${HOME}/.profile" ]; then
            printf '%s\n%s\n' "${path_marker}" "${path_entry}" > "${HOME}/.profile"
            success "Created ${HOME}/.profile with PATH entry"
        else
            step "No shell profile needed PATH update"
        fi
    fi

    # Make xergon-agent available in current session
    export PATH="${XERGON_BIN}:$PATH"
}

remove_from_path() {
    step "Removing PATH entry from shell profiles..."

    for target_file in "${HOME}/.zshrc" "${HOME}/.bashrc" "${HOME}/.bash_profile" "${HOME}/.profile"; do
        if [ -f "$target_file" ]; then
            # Remove the marker line and the export line (in either order)
            if grep -qF "${path_marker}" "$target_file" 2>/dev/null; then
                # Use a temp file approach that works with any sed
                tmp_file="$(mktemp)"
                grep -vF "${path_marker}" "$target_file" | grep -vF "${path_entry}" > "$tmp_file" || true
                mv "$tmp_file" "$target_file"
                success "Cleaned ${target_file}"
            fi
        fi
    done
}

# ── Download Binary ────────────────────────────────────────────────────────────

download_binary() {
    local os="$1"
    local arch="$2"

    local tarball_name="${BINARY_NAME}-${os}-${arch}.tar.gz"
    local download_url="${XERGON_BASE_URL}/${XERGON_VERSION}/download/${tarball_name}"

    step "Downloading ${tarball_name}..."

    # Create temp directory for download
    TMPDIR="$(mktemp -d)"
    trap 'rm -rf "${TMPDIR}"' EXIT

    # Download with retry
    local retries=3
    local attempt=1

    while [ "$attempt" -le "$retries" ]; do
        info "Download attempt ${attempt}/${retries}..."

        if curl --fail --silent --show-error --location --progress-bar \
            -o "${TMPDIR}/${tarball_name}" "${download_url}"; then
            break
        fi

        attempt=$((attempt + 1))

        if [ "$attempt" -le "$retries" ]; then
            warn "Download failed, retrying in 3 seconds..."
            sleep 3
        fi
    done

    if [ "$attempt" -gt "$retries" ]; then
        error "Failed to download ${tarball_name} after ${retries} attempts."
        error "URL: ${download_url}"
        error ""
        error "This is expected if no release has been published yet."
        error "The installer structure is ready -- binary distribution requires CI/CD setup."
        error ""
        error "To build locally: cd xergon-agent && cargo build --release"
        exit 1
    fi

    # Extract
    step "Extracting binary..."
    tar -xzf "${TMPDIR}/${tarball_name}" -C "${TMPDIR}"

    # Install
    step "Installing to ${XERGON_BIN}/"
    chmod +x "${TMPDIR}/${BINARY_NAME}"
    mv "${TMPDIR}/${BINARY_NAME}" "${XERGON_BIN}/${BINARY_NAME}"

    success "Installed ${BINARY_NAME} ${XERGON_VERSION} (${os}/${arch})"
}

# ── Install Command ────────────────────────────────────────────────────────────

do_install() {
    banner
    info "Installing Xergon Network agent..."
    printf "\n"

    detect_os
    detect_arch
    check_prereqs
    create_dirs
    generate_default_config
    create_wallet_placeholder
    download_binary "$OS" "$ARCH"
    add_to_path

    printf "\n"
    info "Installation complete!"
    printf "\n"
    printf "${DIM}  Installed to: ${XERGON_HOME}/${RESET}\n"
    printf "${DIM}  Binary:      ${XERGON_BIN}/${BINARY_NAME}${RESET}\n"
    printf "${DIM}  Config:      ${XERGON_HOME}/config.toml${RESET}\n"
    printf "\n"

    if [ ! -f "${XERGON_HOME}/wallet.json" ] || grep -q '"public_address": null' "${XERGON_HOME}/wallet.json" 2>/dev/null; then
        printf "${YELLOW}${BOLD}  Next step: run 'xergon-agent setup' to configure your node.${RESET}\n"
    fi

    printf "\n"
    printf "${CYAN}  To activate in current shell:${RESET}\n"
    printf "    ${BOLD}source ~/.bashrc${RESET}    (or ~/.zshrc)\n"
    printf "\n"
    printf "${CYAN}  Then:${RESET}\n"
    printf "    ${BOLD}xergon-agent setup${RESET}     -- interactive first-run config\n"
    printf "    ${BOLD}xergon-agent --help${RESET}    -- see all commands\n"
    printf "\n"
}

# ── Update Command ─────────────────────────────────────────────────────────────

do_update() {
    banner
    info "Updating Xergon Network agent..."
    printf "\n"

    if [ ! -f "${XERGON_BIN}/${BINARY_NAME}" ]; then
        error "Xergon agent not found at ${XERGON_BIN}/${BINARY_NAME}"
        error "Run install first: curl -sSL https://degens.world/xergon | sh"
        exit 1
    fi

    detect_os
    detect_arch
    check_prereqs

    # Show current version if available
    if "${XERGON_BIN}/${BINARY_NAME}" --version >/dev/null 2>&1; then
        local current_version
        current_version="$("${XERGON_BIN}/${BINARY_NAME}" --version 2>/dev/null | head -1)"
        info "Current version: ${current_version}"
    fi

    # Backup existing binary
    if [ -f "${XERGON_BIN}/${BINARY_NAME}" ]; then
        step "Backing up existing binary..."
        cp "${XERGON_BIN}/${BINARY_NAME}" "${XERGON_BIN}/${BINARY_NAME}.bak"
    fi

    download_binary "$OS" "$ARCH"

    # Preserve config and wallet
    generate_default_config
    create_wallet_placeholder

    printf "\n"
    info "Update complete!"
    printf "\n"
    printf "${CYAN}  Run 'xergon-agent --version' to confirm.${RESET}\n"
    printf "\n"
}

# ── Uninstall Command ──────────────────────────────────────────────────────────

do_uninstall() {
    banner
    warn "This will remove Xergon Network from your system."
    printf "\n"

    # Confirm uninstall
    printf "${YELLOW}${BOLD}  Are you sure you want to uninstall? [y/N] ${RESET}"
    read -r confirmation </dev/tty 2>/dev/null || confirmation="n"

    case "$confirmation" in
        y|Y|yes|YES) ;;
        *)
            info "Uninstall cancelled."
            exit 0
            ;;
    esac

    printf "\n"

    # Remove PATH entries
    remove_from_path

    # Remove binary
    if [ -f "${XERGON_BIN}/${BINARY_NAME}" ]; then
        step "Removing binary: ${XERGON_BIN}/${BINARY_NAME}"
        rm -f "${XERGON_BIN}/${BINARY_NAME}"
        rm -f "${XERGON_BIN}/${BINARY_NAME}.bak"
        success "Binary removed"
    fi

    # Ask about data removal
    printf "\n"
    printf "${YELLOW}${BOLD}  Remove all data including config and wallet? [y/N] ${RESET}"
    read -r remove_data </dev/tty 2>/dev/null || remove_data="n"

    case "$remove_data" in
        y|Y|yes|YES)
            if [ -d "${XERGON_HOME}" ]; then
                step "Removing directory: ${XERGON_HOME}"
                rm -rf "${XERGON_HOME}"
                success "All data removed"
            fi
            ;;
        *)
            info "Keeping ${XERGON_HOME}/ (config, wallet, data preserved)"
            ;;
    esac

    printf "\n"
    info "Xergon Network has been uninstalled."
    printf "\n"
    printf "${DIM}  To reinstall: curl -sSL https://degens.world/xergon | sh${RESET}\n"
    printf "\n"
}

# ── Help Command ───────────────────────────────────────────────────────────────

do_help() {
    banner
    printf "  ${BOLD}USAGE${RESET}\n"
    printf "    curl -sSL https://degens.world/xergon | sh            # install\n"
    printf "    curl -sSL https://degens.world/xergon | sh -s -- update    # update\n"
    printf "    curl -sSL https://degens.world/xergon | sh -s -- uninstall  # uninstall\n"
    printf "\n"
    printf "  ${BOLD}COMMANDS${RESET}\n"
    printf "    install     Install xergon-agent (default) \n"
    printf "    update      Update to latest version\n"
    printf "    uninstall   Remove xergon-agent from system\n"
    printf "    help        Show this help message\n"
    printf "\n"
    printf "  ${BOLD}OPTIONS${RESET}\n"
    printf "    XERGON_VERSION=v0.1.0  Install specific version (default: latest)\n"
    printf "\n"
    printf "  ${BOLD}WHAT GETS INSTALLED${RESET}\n"
    printf "    ~/.xergon/bin/xergon-agent   -- the binary\n"
    printf "    ~/.xergon/config.toml        -- agent configuration\n"
    printf "    ~/.xergon/wallet.json        -- encrypted wallet (generated on setup)\n"
    printf "    ~/.xergon/data/              -- settlement ledger, peer data\n"
    printf "\n"
    printf "  ${BOLD}REQUIREMENTS${RESET}\n"
    printf "    - macOS or Linux\n"
    printf "    - amd64 or arm64 architecture\n"
    printf "    - curl, tar, sh\n"
    printf "\n"
}

# ── Main ───────────────────────────────────────────────────────────────────────

main() {
    # Parse command (first argument, default: install)
    COMMAND="${1:-install}"

    case "$COMMAND" in
        install|"")   do_install   ;;
        update)       do_update    ;;
        uninstall)    do_uninstall ;;
        help|--help|-h) do_help    ;;
        *)
            error "Unknown command: ${COMMAND}"
            error "Run with 'help' for usage information."
            exit 1
            ;;
    esac
}

main "$@"
